apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-04-28T10:13:32Z"
  labels:
    app: nginx
    run: mypod
  name: mypod
  namespace: default
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicationController
    name: myapp-rc
    uid: 4b1e4ddd-d6a2-4fb1-8eae-52fc04e7d77a
  resourceVersion: "10644"
  uid: 22f6cd05-a0d4-4544-8aa7-9a62ddf31eca
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: mypod
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-vdm7g
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: pool-gm5b5rjel-co95f
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-vdm7g
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-04-28T10:13:32Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-04-28T10:13:35Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-04-28T10:13:35Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-04-28T10:13:32Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://45ba8edaf6d7b6358985aac46539bb5fcee856b5c7a4d94ce37aa01571a89d72
    image: docker.io/library/nginx:latest
    imageID: docker.io/library/nginx@sha256:859ab6768a6f26a79bc42b231664111317d095a4f04e4b6fe79ce37b3d199097
    lastState: {}
    name: mypod
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-04-28T10:13:35Z"
  hostIP: 10.122.0.3
  phase: Running
  podIP: 10.244.0.203
  podIPs:
  - ip: 10.244.0.203
  qosClass: BestEffort
  startTime: "2022-04-28T10:13:32Z"
