apiVersion: batch/v1
kind: CronJob
metadata:
  name: myapp-cronjob
spec:
  schedule: "* * * * *"
  # successfulJobsHistoryLimit: 5
  # failedJobsHistoryLimit: 2
  # suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args: ["sleep","30"]
          restartPolicy: OnFailure