apiVersion: apps/v1
kind: Deployment
metadata:
  name:  myapp-deployment
  annotations:
    kubernetes.io/change-cause: nginx:mainline-alpine modified image
spec:
  replicas: 5
  # strategy:
  #   rollingUpdate:
  #     maxSurge: 25%
  #     maxUnavailable: 25%
  #   type: RollingUpdate
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app:  myapp
    spec:
      containers:
      - name:  nginx-container
        image:  nginx:mainline-alpine
