apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  containers:
  - name: nginx-container
    image: nginx
    env:
    - name:  DB_USER
      value: admin
    - name:  DB_PASS
      value: secret