apiVersion: v1
kind: Pod
metadata:
  name: myapp1
  labels:
    app: myapp
spec:
  containers:
  - name: container1
    image: nginx
  - name: container2
    image: ubuntu
    command: ["sleep", "3600"]
