apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  containers:
  - name: myapp
    image: nginx
    # envFrom:
    # - secretRef:
    #     name: mysecret
    # env:
    # - name: DB_USER
    #   valueFrom:
    #     secretKeyRef:
    #       key: DB_USER
    #       name: mysecret
    # - name: DB_PASS
    #   valueFrom:
    #     secretKeyRef:
    #       key: DB_PASS
    #       name: mysecret
    volumeMounts:
    - name: test
      mountPath: "/secret"
      readOnly: true

  volumes:
  - name: test
    secret:
      secretName: mysecret
      items:
        - key: DB_USER
          path: DB_USER
      
 

