apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-rs
spec:
  replicas: 2
  selector:
    matchExpressions:
    - key: app
      operator: In
      values: 
      - myapp
    - key: tier
      operator: NotIn
      values: 
      - backend
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
    spec:
      containers:
      - name: nginx-container
        image: nginx